---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgBJkqY8dvtjXlsEoE/ZJOoNG2v+vKD7Nss98qQTwkfhGbrnGGipVHX2ixeqhlxLE6zL7b9jrvjb9vUAgsE9H+kuTtmqtNEpu3byJWqOOSXTAQZgsGI9J8ho1NQ5Kh5EfJfaIEWqRZwhZwxctNzXcfdkC58sQtpbXsDZjaPg/SyCbdllR8jmSNBsHFgRU1jKIIn8kGxo26GVkniY24iQM2+2xlURxTOjQd9JyDjf7ZXrm6ceYdY4PZ3Y82KDJxwSEQOrajpOjI27PNcVBvxr7S1SHtmTB6WD3LYjZIvoJNOe0HNGBFDOG6W64ey4Fr9RsX55q6J3xBk+wp5tNuGeKusZehCMfWeiI2pXQekBEveHvda7HW2jZRIF5/WhGH12OkytJuQXm3mkMtOQPfIj9g3fABUTXW6xWGFEhgFkae9xVTWtfkI6gM8F7UlNi4szH97qdvaG+Mr23EP3o9NFtSG6A/mbeRq7jQ72WXYC+cHW4qZeOXmm57cFLswA1zvejCzcEsAHJ4eORd9jw2Vclk0KZgu/kLyDJZ4AvWSiHZ3S9E3fu4MuntgQ2LXz3tzCi5jEWxqDr+ZLRycu/BUZMUj4xXjXnk3jy6GBfGc9pMesvKxofDHJkXXvNeOmn+6E61fmUMTiIIkSZYUiUm4nP5eNwfClDhoC4rufML9gUSm75Q3MKMjl1SmGAmbqn8Xx0FEqaBqAOwbJOGhfs4FTceXDsJ/INVLPXgc3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
